<a href="https://colab.research.google.com/github/Drago-Narmadi/HandsOn-Programing/blob/main/Data%20Structures%20R(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix

In [ ]:
x <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3)
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [ ]:
x <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3)
print(x)
print(x[1,3])
print(x[1,])
print(x[,1])

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] 5
[1] 1 3 5
[1] 1 2


In [ ]:
x <- matrix(c(1,2,3,4,5,6),nrow =2,ncol =3)
print(t(x))

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


In [ ]:
a <- matrix(c(8, 0, 2, 5), ncol = 2)
a <- t(a)
print(a[2, 1])

[1] 2


In [ ]:
x <- data.frame("id"=1:2,"name"=c("James","Amy"),"age"=c(42,18))
print(x)

  id  name age
1  1 James  42
2  2   Amy  18


In [ ]:
x <- data.frame("id" = 1:2, "name" = c("James", "Amy"), "age" = c(42,18))
#Second column
print(x[[2]])
print("------")
#the name column
print(x[["name"]])
print("------")
#the same as
print(x$name)
print("------")
print(x[2])
print("------")
print(x[[2,3]])

[1] "James" "Amy"  
[1] "------"
[1] "James" "Amy"  
[1] "------"
[1] "James" "Amy"  
[1] "------"
   name
1 James
2   Amy
[1] "------"
[1] 18


In [ ]:
s <- readline('stdin')
s <- as.integer(s[1])
x <- data.frame(
 "name" = c("James", "Amy", "David", "Bob", "John"),
"year" = c("1988","2001", "1996", "2004", "1999"))
 print(paste(x[[s,1]],x[[s,2]],sep=""))

stdin1
[1] "James1988"


In [ ]:
x <- data.frame(
  "product"=c("Banana", "Apple", "Orange"),
  "price"=c(5.99, 2.49, 3.0))
print(x$price[2])

[1] 2.49


In [ ]:
x <- data.frame("id"=1:2,"name"=c("James","Amy"),"age"=c(42,18))
x$country <- c("USA","Italy")
print(x[x$age>21,])
subset(x,age>21)

  id  name age country
1  1 James  42     USA


id name  age country
1 1  James 42  USA

In [1]:
x <- data.frame("id"=1:2,"name"=c("James","Amy"),"age"=c(42,18))
print(mean(x$age))

[1] 30


In [11]:
x <- data.frame("id" = 1:3, "name" = c("James", "Amy", "Bob"), "age" = c(42,18, 33))
gender <- factor(c("Male", "Female", "Male"))
print(levels(gender))
print("----------")
print(table(gender))
print("----------")
x$gender <- gender
print(x)

[1] "Female" "Male"  
[1] "----------"
gender
Female   Male 
     1      2 
[1] "----------"
  id  name age gender
1  1 James  42   Male
2  2   Amy  18 Female
3  3   Bob  33   Male


The given code defines a dataframe of product prices. It includes two columns: price and tax.
You need to create a new column for the dataframe called total, which should hold the sum of the price and tax columns for each row.
Then, output the mean value of the total column.

In [12]:
products <- data.frame(
  "id" = seq(1:8),
  "price" = c(8000,3500,1200,19000,5000,4800,6700,9300),
  "tax" = c(300,400,200,500,250,200,550,400)
)
products$total <- products$price + products$tax
print(mean(products$total))

[1] 7537.5


In [13]:
x <- matrix(c(3, 1, 0, 8, 5, 3), nrow = 3)
print(x[3, 1])

[1] 0


In [14]:
x <- data.frame(
    "a" = c(7, 42, 3, 5),
    "b" = c("a","b","c","d")
)
y <- subset(x, a < 10)
z <- max(y$a)
print(min(mean(y$a), z))

[1] 5


You have a dataframe that includes grades of students.
Your program needs to take a number as input, and output the number of students who have a grade greater than the given input.
For example, for the input 89, the output should be:
[1] 3
as 3 students have grades greater than 89.

In [17]:
input <- readline('stdin')
x <- as.integer(input[1])

data <- data.frame(
  id = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  grade = c(75, 26, 54, 90, 86, 93, 48, 71, 66, 99)
)

count <- length(data$grade[data$grade > x])

print(count)

stdin56
[1] 7
